### ISSUE TITLE
FATAL: password authentication / DETAIL: Role “” does not exist

### ISSUE THREAD

**Issue by ippocratis** [alextran1502/immich#17]
i cant access http://ip:2283 , https://ip:2284 nor can  create a user
lsogs say i didnt configure database properly

```
immich_server    | 
proxy_nginx      | 2022/02/10 10:31:38 [error] 22#22: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.32, server: , request: "GET / HTTP/1.1", upstream: "http://.21.0.4:3000/", host: "192.168.1.24:2283"
proxy_nginx      | 192.168.1.32 - - [10/Feb/2022:10:31:38 +0000] "GET / HTTP/1.1" 502 559 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" "-"
proxy_nginx      | 2022/02/10 10:31:38 [error] 22#22: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.32, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://xxx.21.0.4:3000/favicon.ico", host: "192.168.1.24:2283", referrer: "http://192.168.1.24:2283/"
proxy_nginx      | 192.168.1.32 - - [10/Feb/2022:10:31:38 +0000] "GET /favicon.ico HTTP/1.1" 502 559 "http://192.168.1.24:2283/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" "-"
```

and

```
immich_postgres  | 2022-02-10 10:31:59.225 UTC [32] FATAL:  password authentication failed for user "immich"
immich_postgres  | 2022-02-10 10:31:59.225 UTC [32] DETAIL:  Role "immich" does not exist.
immich_postgres  | 	Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
immich_server    | [Nest] 29  - 02/10/2022, 10:31:59 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
immich_server    | error: password authentication failed for user "immich"
immich_server    |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/src/parser.ts:369:69)
immich_server    |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/src/parser.ts:188:21)
immich_server    |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:103:30)
immich_server    |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)
immich_server    |     at Socket.emit (node:events:520:28)
immich_server    |     at addChunk (node:internal/streams/readable:315:12)
immich_server    |     at readableAddChunk (node:internal/streams/readable:289:9)
immich_server    |     at Socket.Readable.push (node:internal/streams/readable:228:10)
immich_server    |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
immich_postgres  | 2022-02-10 10:32:02.520 UTC [33] FATAL:  password authentication failed for user "immich"
immich_postgres  | 2022-02-10 10:32:02.520 UTC [33] DETAIL:  Role "immich" does not exist.
immich_postgres  | 	Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
```
my .env

```
NODE_ENV=development

# Database
DB_USERNAME=immich
DB_PASSWORD=immich
DB_DATABASE_NAME=immich

# Upload File Config
UPLOAD_LOCATION=./upload

# JWT SECRET
JWT_SECRET=immich
```

my docker-compose.yml

```
  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: immich
      POSTGRES_USER: immich
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - immich_network
```
most likely i missed something
any ideas apreciated
