### ISSUE TITLE
[BUG] immich-web error

### ISSUE THREAD

**Issue by Antonet99** [alextran1502/immich#178]
**Describe the bug**

I was looking to test the app, so I deployed it on a VM running Ubuntu Server 22.04 with the docker-compose.yml and the .env files. I obv adjusted them to my settings (code attached). 

When I try to open the web app at http://IP:2285 to register the first user, I have two problem:

```
FetchError: request to http://192.168.1.65:2283/user/count failed, reason: socket hang up
docker-immich-web-1            |     at ClientRequest.<anonymous> (file:///usr/src/app/build/shims-eb608bdd.js:6246:11)
docker-immich-web-1            |     at ClientRequest.emit (node:events:527:28)
docker-immich-web-1            |     at Socket.socketOnEnd (node:_http_client:478:9)
docker-immich-web-1            |     at Socket.emit (node:events:539:35)
docker-immich-web-1            |     at endReadableNT (node:internal/streams/readable:1345:12)
docker-immich-web-1            |     at processTicksAndRejections (node:internal/process/task_queues:83:21)


FetchError: request to http://192.168.1.65:2283/user/count failed, reason: read ECONNRESET
docker-immich-web-1            |     at ClientRequest.<anonymous> (file:///usr/src/app/build/shims-eb608bdd.js:6246:11)
docker-immich-web-1            |     at ClientRequest.emit (node:events:527:28)
docker-immich-web-1            |     at Socket.socketErrorListener (node:_http_client:454:9)
docker-immich-web-1            |     at Socket.emit (node:events:527:28)
docker-immich-web-1            |     at emitErrorNT (node:internal/streams/destroy:157:8)
docker-immich-web-1            |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
docker-immich-web-1            |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

<img width="1440" alt="screen" src="https://user-images.githubusercontent.com/50658637/169841377-2296b52f-1a92-4b40-b6b1-f51095591a2f.png">

Am I missing something? I can't find a solution!

docker-compose.yml
```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:latest
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    expose:
      - "3000"
    volumes:
      - /home/user1/prova/immich:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    networks:
      - immich-network
    restart: always

  immich-microservices:
    image: altran1502/immich-microservices:latest
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    expose:
      - "3001"
    volumes:
      - /home/user1/prova/immich:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    networks:
      - immich-network
    restart: always

  immich-web:
    image: altran1502/immich-web:latest
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    ports:
      - 2285:3000
     networks:
      - immich-network
    restart: always


  redis:
    container_name: immich_redis
    image: redis:6.2
    networks:
      - immich-network
    restart: always
    

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: user
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - immich-network

  nginx:
    container_name: proxy_nginx
    image: nginx:latest
    volumes:
      - /home/user1/prova/nginx/settings/nginx-conf:/etc/nginx/conf.d
    ports:
      - 2283:80
      - 2284:443
         logging:
      driver: none
    networks:
      - immich-network
    depends_on:
      - immich-server
    restart: always

networks:
  immich-network:
volumes:
  pgdata:
```
