### ISSUE TITLE
[Bug] Problem with deploying Immich using `podman-compose`

### ISSUE THREAD

**Issue by bertmelis** [alextran1502/immich#277]
After launching Immich using podman-compose, containers are started but as soon as I try to access the webpage, (at least) the web container exits because of `Error: listen EADDRINUSE: address already in use 0.0.0.0:3000`

```
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at doListen (node:net:1559:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1399:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3000
}
```

podman-compose.yml:
```
version: "3.8"

services:
  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  immich-server:
    image: altran1502/immich-server:latest
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      #- database
    #restart: always

  immich-microservices:
    image: altran1502/immich-server:latest
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis

    immich-web:
    image: altran1502/immich-web:latest
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env

  nginx:
    container_name: proxy_nginx
    image: nginx:latest
    volumes:
      - ./settings/nginx-conf:/etc/nginx/conf.d
    ports:
      - 2283:80
      - 2284:443
    logging:
      driver: none
    depends_on:
      - immich-server
```

.env
```
###################################################################################
# Database
###################################################################################
DB_HOSTNAME=<redacted
DB_USERNAME=<redacted>
DB_PASSWORD=<redacted>
DB_DATABASE_NAME=immich

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

###################################################################################
# Upload File Config
###################################################################################
UPLOAD_LOCATION=/mnt/data/photos

###################################################################################
# JWT SECRET
###################################################################################
JWT_SECRET=<redacted>

###################################################################################
# MAPBOX
####################################################################################
# ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
ENABLE_MAPBOX=false
MAPBOX_KEY=

###################################################################################
# WEB
###################################################################################
# This is the URL of your vm/server where you host Immich, so that the web frontend
# know where can it make the request to.
# For example: If your server IP address is 10.1.11.50, the environment variable will
# be VITE_SERVER_ENDPOINT=http://10.1.11.50:2283/api
VITE_SERVER_ENDPOINT=http://<local ip>:2283/api
```

`sudo netstat -pna | grep 3000` shows no other open ports

I'm trying to set up Immich on Rocky Linux (RHEL) with Podman. I use an external database.

**Comment by alextran1502** [comment]
I haven't tested on Podman nor used it before. Is podman-compose similar to docker-compose? If so, if you create a dedicated network, would it work?

**Comment by alextran1502** [comment]
We can try to troubleshoot by commenting out `immich-microservices` since it used the same port as the `immich-server`. In `docker-compose`, if you don't expose the port, it won't be conflicted, so this might be different with podman

**Comment by bertmelis** [comment]
> I haven't tested on Podman nor used it before. Is podman-compose similar to docker-compose? If so, if you create a dedicated network, would it work?

It uses the same (basic) commands but underlying it uses podman of course. `podman-compose up` creates the dedicated network, but it is one network for the whole pod. All the containers in the pod use the same port space. Microservices is started first and claims port 3000. Afterwards, nor server nor web can't use that port anymore even though these ports are not exposed outside the pod.

**Comment by alextran1502** [comment]
I think the conflict here is internally to the pod's network

**Comment by bertmelis** [comment]
- `podman create network immich_network`
- added `network_mode: immich_network` to all the containers in the compose-file.


for both microservices and server.
```
Error: connect ECONNREFUSED 127.0.0.1:6379
```

PS I might want to move this to discussions...

**Comment by zackpollard** [comment]
If all we need to do is change the default ports for the servers then i'm not against that, it's a shame that podman doesn't work similarly to docker here as there is no need to have all the containers running on the same IP (which is presumably what's happening here). Is there no alternative way to set this up in podman so each container gets its own IP and they can communicate with internal dns, like what happens with docker?

**Comment by bertmelis** [comment]
It is possible, but not if you're rootless. I'm still looking for a workaround though.

**Comment by alextran1502** [comment]
If you cannot find a way to work around it, let us know and we will consider changing the port of those containers.

**Comment by bertmelis** [comment]
I haven't found any clean solutions yet except by creating an abundance of networks.

It would be much cleaner if the ports changed. But before committing this, can I test this myself?

And if it works, can I persuade you with a few 'buy-me-a-coffees'?

**Comment by alextran1502** [comment]
Let me build an image with different port and I will write up an instruction of how to test

**Comment by alextran1502** [comment]
Ok, so I've just changed the port on `immich-server` to `3001` and `immich-microservices` to `3002`. 

It is building in this PR #278 

Once you see the check mark is green in the checks section it means that the build is done.

All you have to do on your side is to change the tags of those images to `staging` i.e `altran1502/immich-server:staging` and use this Nginx conf file to replace the one in the main repo.

```nginx

map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

# events {
#   worker_connections 1000;
# }

server {

  gzip on;
  gzip_min_length 1000;
  gunzip on;

  client_max_body_size 50000M;

  listen 80;
  access_log off;

  location /api {

    # Compression
    gzip_static on;
    gzip_min_length 1000;
    gzip_comp_level 2;

    proxy_buffering off;
    proxy_buffer_size 16k;
    proxy_busy_buffers_size 24k;
    proxy_buffers 64 4k;
    proxy_force_ranges on;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;

    rewrite /api/(.*) /$1 break;

    proxy_pass http://immich-server:3001;
  }

  location / {

    # Compression
    gzip_static on;
    gzip_min_length 1000;
    gzip_comp_level 2;

    proxy_buffering off;
    proxy_buffer_size 16k;
    proxy_busy_buffers_size 24k;
    proxy_buffers 64 4k;
    proxy_force_ranges on;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;

    proxy_pass http://immich-web:3000;
  }
}
```

Let me know how it goes.

**Comment by bertmelis** [comment]
Works! You're the man!

One thing I had to change though. I specified a custom `redis.conf` file and commented out `bind 127.0.0.1 -::1`.

On container-compose.yml:
```
  redis:
    container_name: immich_redis
    image: redis:6.2
    volumes:
      -  ./settings/redis:/usr/local/etc/redis:Z
    restart: always
```

(ref: https://stackoverflow.com/questions/50559985/unable-to-connect-to-redis-from-another-docker-container)
