### ISSUE TITLE
[BUG] Server can't connect after v1.15.0_21-dev

### ISSUE THREAD

**Issue by xpwmaosldk** [alextran1502/immich#285]
Hi, My environment is MacOS.

Here is my docker-compose.yml
```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: [ "/bin/sh", "./start-server.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: [ "/bin/sh", "./start-microservices.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  # immich-machine-learning:
  #   image: altran1502/immich-machine-learning:release
  #   entrypoint: [ "/bin/sh", "./entrypoint.sh" ]
  #   volumes:
  #     - ${UPLOAD_LOCATION}:/usr/src/app/upload
  #   env_file:
  #     - .env
  #   environment:
  #     - NODE_ENV=production
  #   depends_on:
  #     - database
  #   restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: [ "/bin/sh", "./entrypoint.sh" ]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:80
      - 2284:443
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:

```

And server start well but I got message `immich_proxy exited with code 0` then I can't connect server form mobile.
![1](https://user-images.githubusercontent.com/13146337/176636131-00f96a6c-ea95-482c-a9f8-fe4db8b26ab0.png)

Mobile ping(api/server-info/ping) response `Connection refused`
Web is same(ERR_CONNECTION_REFUSED)

I didn't changed any setting manually before and after.
