### ISSUE TITLE
[BUG] Since 1.16 newly uploaded images aren't showing up.

### ISSUE THREAD

**Issue by base1983** [alextran1502/immich#312]
**Describe the bug**

**Task List**
- [x] I have read thoroughly the README setup and installation instructions.
- [x] If my setup is different, I have included my docker-compose file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I have done a docker-compose pull to update the deployment. but even with latest build it does not show me any new images I upload. No matter if it's via iPhone of Web (Windows 11). Asset count does increase but the image thumbnail doesn't show.

This is my docker-compose.yml:
```
services:
  immich-server:
    image: altran1502/immich-server:latest
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    expose:
      - "3000"
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    networks:
      - immich-network
    restart: always

  immich-microservices:
    image: altran1502/immich-microservices:latest
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    expose:
      - "3001"
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    networks:
      - immich-network
    restart: always

  immich-web:
    image: altran1502/immich-web:latest
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    ports:
      - 2285:3000
    networks:
      - immich-network
    restart: always


  redis:
    container_name: immich_redis
    image: redis:6.2
    networks:
      - immich-network
    restart: always


  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - immich-network

  nginx:
    container_name: proxy_nginx
    image: nginx:latest
    volumes:
      - ./settings/nginx-conf:/etc/nginx/conf.d
    ports:
      - 2283:80
      - 2284:443
    logging:
      driver: none
    networks:
      - immich-network
    depends_on:
      - immich-server
    restart: always

networks:
  immich-network:
volumes:
```
And this is my .env file:
```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:latest
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    expose:
      - "3000"
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    networks:
      - immich-network
    restart: always

  immich-microservices:
    image: altran1502/immich-microservices:latest
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    expose:
      - "3001"
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    networks:
      - immich-network
    restart: always

  immich-web:
    image: altran1502/immich-web:latest
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    ports:
      - 2285:3000
    networks:
      - immich-network
    restart: always


  redis:
    container_name: immich_redis
    image: redis:6.2
    networks:
      - immich-network
    restart: always


  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - immich-network

  nginx:
    container_name: proxy_nginx
    image: nginx:latest
    volumes:
      - ./settings/nginx-conf:/etc/nginx/conf.d
    ports:
      - 2283:80
      - 2284:443
    logging:
      driver: none
    networks:
      - immich-network
    depends_on:
      - immich-server
    restart: always

networks:
  immich-network:
volumes:
  pgdata:basemaster@cloud:~/immich/docker$ ^C
basemaster@cloud:~/immich/docker$ cat .env
###################################################################################
# Database
###################################################################################

DB_USERNAME=postgres
DB_PASSWORD=*******
DB_DATABASE_NAME=immich



###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis





###################################################################################
# Upload File Config
###################################################################################

UPLOAD_LOCATION=/home/basemaster/Library




###################################################################################
# JWT SECRET
###################################################################################

JWT_SECRET=randomstringthatissolongandpowerfulthatnoonecanguess




###################################################################################
# MAPBOX
####################################################################################

# ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
ENABLE_MAPBOX=false
MAPBOX_KEY=




###################################################################################
# WEB
###################################################################################

# This is the URL of your vm/server where you host Immich, so that the web frontend
# know where can it make the request to.
# For example: If your server IP address is 10.1.11.50, the environment variable will
# be VITE_SERVER_ENDPOINT=http://10.1.11.50:2283

VITE_SERVER_ENDPOINT=http://10.0.0.10:2283/api

```

**Comment by base1983** [comment]
I am using Ubuntu 22.04 LTS

**Comment by alextran1502** [comment]
Hello,

Your docker-compose content is out of date.

Can you please refer to this release to update the content and your system https://github.com/alextran1502/immich/releases/tag/v1.15.0_21-dev

**Comment by alextran1502** [comment]
Can you check if they are still missing? Because if it is updated the
count, the record is written into the database and it should pull
everything accordingly.

Other than that, you can check the raw files in the UPLOAD_LOCATION and
reuploading via web

If that is not the case, you will have to create a new instance with fresh
data and reupload everything

**Comment by Seji64** [comment]
I have the exact Same issue.

Env:

```
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=**redacted**
DB_DATABASE_NAME=immich
DB_LOCATION=/opt/immich/database

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

###################################################################################
# Upload File Config
###################################################################################

UPLOAD_LOCATION=/opt/immich/upload

###################################################################################
# JWT SECRET
###################################################################################

JWT_SECRET=**redacted**

###################################################################################
# MAPBOX
####################################################################################

# ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
ENABLE_MAPBOX=true
MAPBOX_KEY=**redacted**

###################################################################################
# WEB
###################################################################################

# This is the URL of your vm/server where you host Immich, so that the web frontend
# know where can it make the request to.
# For example: If your server IP address is 10.1.11.50, the environment variable will
# be VITE_SERVER_ENDPOINT=http://10.1.11.50:2283/api
# !CAUTION! THERE IS NO FORWARD SLASH AT THE END

VITE_SERVER_ENDPOINT=https://photos.apps.home.tihoda.de/api
```


docker-compose:
```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:latest
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    networks:
      - immich-network
    restart: always

  immich-microservices:
    image: altran1502/immich-microservices:latest
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    networks:
      - immich-network
    restart: always

  immich-web:
    image: altran1502/immich-web:latest
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    networks:
      - immich-network
    restart: always


  redis:
    container_name: immich_redis
    image: redis:6.2
    networks:
      - immich-network
    restart: always
    

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ${DB_LOCATION}:/var/lib/postgresql/data
    networks:
      - immich-network
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:80
    depends_on:
      - immich-server
    networks:
      - immich-network
    restart: always

networks:
  immich-network:
```
