### ISSUE TITLE
[BUG] Failure to build app on RPi4, Ubuntu 21.10 Server. Log: Error: Unsupported system: cpu-linux-arm64

### ISSUE THREAD

**Issue by darrylgibbs** [alextran1502/immich#94]
**Describe the bug**
Following the install instructions exactly, I get an error when building the app.  

The error is as follows, on steap 7/9: RUN npm install
The command '/bin/sh -c npm install' returned a non-zero code: 1
ERROR: Service 'immich_microservices' failed to build : Build failed

Docker-compose.yml is unchanged, and .env has a DB name entered, a JWT code and commented out MAPBOX.

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.10 Raspberry Pi 4 edition

**Additional context**
![Screenshot 2022-03-30 113956](https://user-images.githubusercontent.com/9167471/160861565-3a18ed25-a079-40f4-8b1d-9f83e3c947e8.png)

How do I procede?  am I doing something wrong here?

**Comment by alextran1502** [comment]
You are not doing anything wrong, TensorFlow 2 currently doesn't support Rpi4 64bit

Can you comment out the section below in `docker-compose` file and try again? This will run the server for core backup operation but the object detection and image tagging will be disabled.

I am following the process of supporting Tensorflow 2 in Docker for arm64-v7

```
  immich_microservices:
    image: immich-microservices:1.4.0
    build:
      context: ../microservices
      dockerfile: ../microservices/Dockerfile
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    expose:
      - "3001"
    volumes:
      - ../microservices:/usr/src/app
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    networks:
      - immich_network
```
